// Copyright 2006 Nemanja Trifunovic

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#pragma once
#include <ice/string_view.h>
#include <ice/utf8/checked.h>
#include <ice/utf8/unchecked.h>
#include <string>
#include <system_error>

namespace ice {

// Converts an UTF-8 string to a UTF-16 string. Throws on error.
std::string convert(const ice::u16string_view src);

// Converts an UTF-8 string to a UTF-16 string. Stops on error.
std::string convert(const ice::u16string_view src, std::error_code& ec);

// Converts an UTF-16 string to a UTF-8 string. Throws on error.
std::u16string convert(const ice::string_view src);

// Converts an UTF-16 string to a UTF-8 string. Stops on error.
std::u16string convert(const ice::string_view src, std::error_code& ec);

// Returns true when the given string view contains a valid UTF-8 sequence.
bool is_valid_utf8(ice::string_view str);

}  // namespace ice